`default_nettype none
`timescale 1ps/1ps

// Phase 77: .dat-replay testbench
//
// Usage: vvp sim/cosim_dat +hexfile=tests/vec_0000.hex [+cycles=5000]
//
// Loads a hex file at runtime, runs until STOP, then prints:
//   REGSTATE D0=.. D7=.. A0=.. A6=.. A7=.. SR=.. PC=..
//
// The hex file is generated by scripts/gen_init_hex.py from a test vector.
// It embeds the register-load init sequence and the instruction under test.

module cosim_dat_tb;

    logic clk_4x = 0;
    always #5 clk_4x = ~clk_4x;

    logic rst_n = 0;

    logic [31:0] ext_a;
    logic [31:0] ext_d_out;
    logic        ext_d_oe;
    logic        ext_as_n, ext_ds_n, ext_rw;
    logic [2:0]  ext_fc;
    logic [1:0]  ext_siz;
    logic        ext_ecs_n, ext_ocs_n, ext_rstout_n, ext_cbreq_n;
    logic        ext_e, ext_bg_n;
    logic        bus_halted, eu_addr_err, ifu_addr_err;

    logic        eu_stop_out;

    logic        sterm_n  = 1'b1;
    logic        berr_n   = 1'b1;
    logic        halt_n   = 1'b1;
    logic        avec_n   = 1'b1;
    logic        vpa_n    = 1'b1;
    logic [2:0]  ipl_n    = 3'b111;
    logic        br_n     = 1'b1;
    logic        bgack_n  = 1'b1;
    logic        cback_n  = 1'b0;

    localparam int MEM_WORDS = 4096;
    logic [31:0] rom [0:MEM_WORDS-1];

    string hexfile;
    initial begin
        integer i;
        for (i = 0; i < MEM_WORDS; i++) rom[i] = 32'h4E714E71;
        if (!$value$plusargs("hexfile=%s", hexfile))
            hexfile = "tests/smoke.hex";
        $readmemh(hexfile, rom);
    end

    wire [31:0] rd_word = (ext_a[13:2] < MEM_WORDS) ? rom[ext_a[13:2]] : 32'hDEAD_DEAD;

    logic ds_active_r;
    always_ff @(posedge clk_4x or negedge rst_n) begin
        if (!rst_n) ds_active_r <= 1'b0;
        else        ds_active_r <= !ext_ds_n & !ext_as_n;
    end

    wire dsack0_n = ~ds_active_r;
    wire dsack1_n = ~ds_active_r;

    wire [31:0] ext_d_in = (!ext_ds_n & ext_rw) ? rd_word : {32{1'bz}};

    always_ff @(posedge clk_4x) begin
        if (ds_active_r && !ext_ds_n && !ext_as_n && !ext_rw && ext_d_oe) begin
            if (ext_a[13:2] < MEM_WORDS) begin
                case ({ext_siz, ext_a[1:0]})
                    4'b00_00: rom[ext_a[13:2]]        <= ext_d_out;
                    4'b10_00: rom[ext_a[13:2]][31:16] <= ext_d_out[31:16];
                    4'b10_10: rom[ext_a[13:2]][15:0]  <= ext_d_out[15:0];
                    4'b01_00: rom[ext_a[13:2]][31:24] <= ext_d_out[31:24];
                    4'b01_01: rom[ext_a[13:2]][23:16] <= ext_d_out[23:16];
                    4'b01_10: rom[ext_a[13:2]][15:8]  <= ext_d_out[15:8];
                    4'b01_11: rom[ext_a[13:2]][7:0]   <= ext_d_out[7:0];
                    default:  rom[ext_a[13:2]]        <= ext_d_out;
                endcase
            end
        end
    end

    m68030_top #(.POWERON_RSTO_CLKS(40)) u_top (
        .clk_4x       (clk_4x),
        .rst_n        (rst_n),
        .ext_a        (ext_a),
        .ext_d_out    (ext_d_out),
        .ext_d_oe     (ext_d_oe),
        .ext_d_in     (ext_d_in),
        .ext_as_n     (ext_as_n),
        .ext_ds_n     (ext_ds_n),
        .ext_rw       (ext_rw),
        .ext_fc       (ext_fc),
        .ext_siz      (ext_siz),
        .ext_ecs_n    (ext_ecs_n),
        .ext_ocs_n    (ext_ocs_n),
        .ext_rstout_n (ext_rstout_n),
        .ext_cbreq_n  (ext_cbreq_n),
        .ext_e        (ext_e),
        .ext_bg_n     (ext_bg_n),
        .bus_halted   (bus_halted),
        .eu_stop      (eu_stop_out),
        .eu_addr_err  (eu_addr_err),
        .ifu_addr_err (ifu_addr_err),
        .dsack0_n     (dsack0_n),
        .dsack1_n     (dsack1_n),
        .sterm_n      (sterm_n),
        .berr_n       (berr_n),
        .halt_n       (halt_n),
        .avec_n       (avec_n),
        .vpa_n        (vpa_n),
        .ipl_n        (ipl_n),
        .br_n         (br_n),
        .bgack_n      (bgack_n),
        .cback_n      (cback_n)
    );

    // ── Bus logger (optional: set +buslog=1 to enable) ───────────────────────
    logic        as_prev_r;
    logic [31:0] log_addr_r;
    logic [2:0]  log_fc_r;
    logic [1:0]  log_siz_r;
    logic        log_rw_r;
    logic [31:0] log_data_r;
    int          buslog_en;

    always_ff @(posedge clk_4x or negedge rst_n) begin
        if (!rst_n) begin
            as_prev_r  <= 1'b1;
            log_addr_r <= 32'h0;
            log_fc_r   <= 3'b0;
            log_siz_r  <= 2'b0;
            log_rw_r   <= 1'b1;
            log_data_r <= 32'h0;
        end else begin
            as_prev_r <= ext_as_n;
            if (!ext_as_n) begin
                log_addr_r <= ext_a;
                log_fc_r   <= ext_fc;
                log_siz_r  <= ext_siz;
                log_rw_r   <= ext_rw;
                log_data_r <= ext_rw ? rd_word : (ext_d_oe ? ext_d_out : 32'h0);
            end
        end
    end

    initial buslog_en = 0;
    always_ff @(posedge clk_4x) begin
        if (!as_prev_r && ext_as_n && buslog_en) begin
            if (log_rw_r)
                $display("BUS R %h %h fc=%b siz=%b",
                         log_addr_r, log_data_r, log_fc_r, log_siz_r);
            else
                $display("BUS W %h %h fc=%b siz=%b",
                         log_addr_r, log_data_r, log_fc_r, log_siz_r);
        end
    end

    // ── STOP detection ───────────────────────────────────────────────────────
    // eu_stop_out goes high the cycle after STOP first enters the EX stage.
    // At that point all preceding instructions have completed WB and SR is
    // already updated (stop_sr_wr_en fired one cycle earlier).
    // This avoids false positives from 0x4E72 appearing as an immediate value
    // inside a MOVE.L instruction's prefetch stream.
    logic stop_seen = 1'b0;
    always_ff @(posedge clk_4x) begin
        if (eu_stop_out) stop_seen <= 1'b1;
    end

    logic any_addr_err = 1'b0;
    always_ff @(posedge clk_4x) begin
        if (eu_addr_err || ifu_addr_err) any_addr_err <= 1'b1;
    end

    // ── Main ─────────────────────────────────────────────────────────────────
    initial begin
        integer cycles;

        rst_n = 0;
        repeat(20) @(posedge clk_4x);
        #1; rst_n = 1;

        if (!$value$plusargs("cycles=%d", cycles)) cycles = 5000;
        void'($value$plusargs("buslog=%d", buslog_en));

        fork
            begin : blk_timeout
                repeat(cycles) @(posedge clk_4x);
            end
            begin : blk_stop
                wait(stop_seen == 1'b1);
                // eu_stop_out went high when STOP first entered EX; SR is
                // already written.  Give WB one more tick to propagate.
                repeat(4) @(posedge clk_4x);
                disable blk_timeout;
            end
        join

        // Print register state — Python comparator greps for "^REGSTATE"
        $display("REGSTATE D0=%h D1=%h D2=%h D3=%h D4=%h D5=%h D6=%h D7=%h A0=%h A1=%h A2=%h A3=%h A4=%h A5=%h A6=%h A7=%h SR=%h PC=%h",
            u_top.u_eu.u_rf.d_reg[0],
            u_top.u_eu.u_rf.d_reg[1],
            u_top.u_eu.u_rf.d_reg[2],
            u_top.u_eu.u_rf.d_reg[3],
            u_top.u_eu.u_rf.d_reg[4],
            u_top.u_eu.u_rf.d_reg[5],
            u_top.u_eu.u_rf.d_reg[6],
            u_top.u_eu.u_rf.d_reg[7],
            u_top.u_eu.u_rf.a_reg[0],
            u_top.u_eu.u_rf.a_reg[1],
            u_top.u_eu.u_rf.a_reg[2],
            u_top.u_eu.u_rf.a_reg[3],
            u_top.u_eu.u_rf.a_reg[4],
            u_top.u_eu.u_rf.a_reg[5],
            u_top.u_eu.u_rf.a_reg[6],
            u_top.u_eu.u_rf.a7_current,
            u_top.u_eu.u_rf.sr_r,
            u_top.u_eu.u_rf.pc_r);

        if (stop_seen && !any_addr_err)
            $display("PASS  cosim_dat");
        else if (!stop_seen)
            $display("FAIL  cosim_dat (timeout — no STOP)");
        else
            $display("FAIL  cosim_dat (address error)");

        $finish;
    end

endmodule

`default_nettype wire
