// AUTO-GENERATED by scripts/gen_ext_count_overlap_flags.py from
// rtl/m68030_seq.sv's own ext_count always_comb block -- do not
// hand-edit. Re-run the generator (the Makefile rule for
// $(SIM)/ext_count_overlap does this automatically) whenever
// m68030_seq.sv's ext_count chain changes.
//
// 49 branch conditions found; checked as whole,
// verbatim conditions (not individual is_* flags) so legitimate
// refinement pairs like is_X/is_X_long don't false-positive, and
// paired with each branch's own ext_count VALUE expression so a
// same-value overlap (a harmless, structural consequence of how
// if/else-if priority chains work -- see this generator's own
// extract_branch_conditions() docstring) doesn't false-positive
// either. See this generator's own header comment.

// Local passthrough wires for every dut-internal signal the
// branch conditions/values below reference (module ports are
// already testbench-level regs of the same name -- no passthrough
// needed for those).
logic [2:0] cmp2chk2_ext_count; assign cmp2chk2_ext_count = dut.cmp2chk2_ext_count;
logic f_dir; assign f_dir = dut.f_dir;
logic [2:0] f_dn; assign f_dn = dut.f_dn;
logic [3:0] f_group; assign f_group = dut.f_group;
logic [2:0] f_mode; assign f_mode = dut.f_mode;
logic [2:0] f_move_dst_mode_s; assign f_move_dst_mode_s = dut.f_move_dst_mode_s;
logic [2:0] f_reg; assign f_reg = dut.f_reg;
logic [1:0] f_ss; assign f_ss = dut.f_ss;
logic is_abs_long; assign is_abs_long = dut.is_abs_long;
logic is_abs_short; assign is_abs_short = dut.is_abs_short;
logic is_adda_suba_cmpa_imm; assign is_adda_suba_cmpa_imm = dut.is_adda_suba_cmpa_imm;
logic is_addq_subq_ext; assign is_addq_subq_ext = dut.is_addq_subq_ext;
logic is_addq_subq_ext_long; assign is_addq_subq_ext_long = dut.is_addq_subq_ext_long;
logic is_alu_imm_dn; assign is_alu_imm_dn = dut.is_alu_imm_dn;
logic is_alu_mem_src; assign is_alu_mem_src = dut.is_alu_mem_src;
logic is_alu_mem_src_long; assign is_alu_mem_src_long = dut.is_alu_mem_src_long;
logic is_bf; assign is_bf = dut.is_bf;
logic is_branch_l; assign is_branch_l = dut.is_branch_l;
logic is_branch_w; assign is_branch_w = dut.is_branch_w;
logic is_cmp2chk2_idx_full; assign is_cmp2chk2_idx_full = dut.is_cmp2chk2_idx_full;
logic is_cprestore; assign is_cprestore = dut.is_cprestore;
logic is_cpsave; assign is_cpsave = dut.is_cpsave;
logic is_dbcc; assign is_dbcc = dut.is_dbcc;
logic is_imm_g0; assign is_imm_g0 = dut.is_imm_g0;
logic is_imm_g0_absl; assign is_imm_g0_absl = dut.is_imm_g0_absl;
logic is_imm_g0_d16_or_absw; assign is_imm_g0_d16_or_absw = dut.is_imm_g0_d16_or_absw;
logic is_imm_g0_mem; assign is_imm_g0_mem = dut.is_imm_g0_mem;
logic is_jmp_idx; assign is_jmp_idx = dut.is_jmp_idx;
logic is_jsr_idx; assign is_jsr_idx = dut.is_jsr_idx;
logic is_jsr_jmp_d16; assign is_jsr_jmp_d16 = dut.is_jsr_jmp_d16;
logic is_lea_d16; assign is_lea_d16 = dut.is_lea_d16;
logic is_lea_idx; assign is_lea_idx = dut.is_lea_idx;
logic is_link; assign is_link = dut.is_link;
logic is_link_l; assign is_link_l = dut.is_link_l;
logic is_memind_full; assign is_memind_full = dut.is_memind_full;
logic is_move_d16; assign is_move_d16 = dut.is_move_d16;
logic is_move_idx_src; assign is_move_idx_src = dut.is_move_idx_src;
logic is_move_idx_src_memdst_full; assign is_move_idx_src_memdst_full = dut.is_move_idx_src_memdst_full;
logic is_move_mm; assign is_move_mm = dut.is_move_mm;
logic is_move_mm_absl_idxdst_full; assign is_move_mm_absl_idxdst_full = dut.is_move_mm_absl_idxdst_full;
logic is_move_mm_absw_idxdst_full; assign is_move_mm_absw_idxdst_full = dut.is_move_mm_absw_idxdst_full;
logic is_move_mm_d16src_idxdst_full; assign is_move_mm_d16src_idxdst_full = dut.is_move_mm_d16src_idxdst_full;
logic is_move_mm_imml_idxdst_full; assign is_move_mm_imml_idxdst_full = dut.is_move_mm_imml_idxdst_full;
logic is_move_mm_immw_idxdst_full; assign is_move_mm_immw_idxdst_full = dut.is_move_mm_immw_idxdst_full;
logic is_move_mm_pcrel_idxdst_full; assign is_move_mm_pcrel_idxdst_full = dut.is_move_mm_pcrel_idxdst_full;
logic is_move_mm_plainsrc_idxdst_full; assign is_move_mm_plainsrc_idxdst_full = dut.is_move_mm_plainsrc_idxdst_full;
logic is_movem; assign is_movem = dut.is_movem;
logic is_movem_2ext; assign is_movem_2ext = dut.is_movem_2ext;
logic is_movem_3ext; assign is_movem_3ext = dut.is_movem_3ext;
logic is_movem_idx_full; assign is_movem_idx_full = dut.is_movem_idx_full;
logic is_movep; assign is_movep = dut.is_movep;
logic is_moves; assign is_moves = dut.is_moves;
logic is_moves_long_ea; assign is_moves_long_ea = dut.is_moves_long_ea;
logic is_muldiv_imm; assign is_muldiv_imm = dut.is_muldiv_imm;
logic is_muldivl; assign is_muldivl = dut.is_muldivl;
logic is_muldivl_2ext; assign is_muldivl_2ext = dut.is_muldivl_2ext;
logic is_muldivl_3ext; assign is_muldivl_3ext = dut.is_muldivl_3ext;
logic is_muldivl_mem; assign is_muldivl_mem = dut.is_muldivl_mem;
logic is_ori_andi_eori_sr; assign is_ori_andi_eori_sr = dut.is_ori_andi_eori_sr;
logic is_pack_unpk; assign is_pack_unpk = dut.is_pack_unpk;
logic is_pc_rel; assign is_pc_rel = dut.is_pc_rel;
logic is_pea; assign is_pea = dut.is_pea;
logic is_pea_abs_long; assign is_pea_abs_long = dut.is_pea_abs_long;
logic is_rtd; assign is_rtd = dut.is_rtd;
logic is_stop_opcode; assign is_stop_opcode = dut.is_stop_opcode;
logic [2:0] memind_ext_count; assign memind_ext_count = dut.memind_ext_count;
logic [2:0] move_idx_src_memdst_ext_count; assign move_idx_src_memdst_ext_count = dut.move_idx_src_memdst_ext_count;
logic [2:0] move_mm_absl_idxdst_ext_count; assign move_mm_absl_idxdst_ext_count = dut.move_mm_absl_idxdst_ext_count;
logic [2:0] move_mm_d16src_idxdst_ext_count; assign move_mm_d16src_idxdst_ext_count = dut.move_mm_d16src_idxdst_ext_count;
logic [2:0] move_mm_idxdst_ext_count; assign move_mm_idxdst_ext_count = dut.move_mm_idxdst_ext_count;
logic [2:0] move_mm_imml_idxdst_ext_count; assign move_mm_imml_idxdst_ext_count = dut.move_mm_imml_idxdst_ext_count;
logic [2:0] move_mm_immw_idxdst_ext_count; assign move_mm_immw_idxdst_ext_count = dut.move_mm_immw_idxdst_ext_count;
logic [2:0] move_mm_plainsrc_idxdst_ext_count; assign move_mm_plainsrc_idxdst_ext_count = dut.move_mm_plainsrc_idxdst_ext_count;
logic [2:0] move_mm_total_ext_w; assign move_mm_total_ext_w = dut.move_mm_total_ext_w;
logic [2:0] movem_ext_count; assign movem_ext_count = dut.movem_ext_count;

localparam int EXT_COUNT_BRANCH_N = 49;
logic [EXT_COUNT_BRANCH_N-1:0] ext_count_branch_bus;
logic [2:0] ext_count_branch_val [0:EXT_COUNT_BRANCH_N-1];
// Auto-detected catch-all buckets (>= 5 top-level ||'s in the branch's own
// condition) -- excluded from the overlap-check's value-
// disagreement trigger in tb/ext_count_overlap_tb.sv, since a
// broad fallback branch overlapping an earlier, more specific
// branch is expected, harmless chain-priority behavior, not a
// bug (see that testbench's own header comment).
logic [EXT_COUNT_BRANCH_N-1:0] ext_count_branch_is_bucket;
assign ext_count_branch_is_bucket = 49'b0110000000000000000000000000000000000000000000000;
// Format-dependent branches (see FORMAT_SEED_SIGNALS above): a
// later, format-INDEPENDENT branch disagreeing with an EARLIER,
// format-DEPENDENT one is this project's own established
// deliberate-override architecture (Phases 116-147, plan.md),
// not a shadowing bug -- tb/ext_count_overlap_tb.sv's own check
// treats that specific pairing as safe.
logic [EXT_COUNT_BRANCH_N-1:0] ext_count_branch_is_format_dep;
assign ext_count_branch_is_format_dep = 49'b0000000000000000000000000000000000000001111111111;
// KNOWN_REFINEMENT_PAIRS (see that constant's own comment above): branch i is safely shadowed specifically when branch ext_count_branch_shadow_of[i] (a strict earlier refinement of it) has already won -- -1 means no such relationship.
int ext_count_branch_shadow_of [0:EXT_COUNT_BRANCH_N-1];
initial begin
    ext_count_branch_shadow_of[0] = -1;
    ext_count_branch_shadow_of[1] = -1;
    ext_count_branch_shadow_of[2] = -1;
    ext_count_branch_shadow_of[3] = -1;
    ext_count_branch_shadow_of[4] = -1;
    ext_count_branch_shadow_of[5] = -1;
    ext_count_branch_shadow_of[6] = -1;
    ext_count_branch_shadow_of[7] = -1;
    ext_count_branch_shadow_of[8] = -1;
    ext_count_branch_shadow_of[9] = 8;
    ext_count_branch_shadow_of[10] = -1;
    ext_count_branch_shadow_of[11] = -1;
    ext_count_branch_shadow_of[12] = -1;
    ext_count_branch_shadow_of[13] = -1;
    ext_count_branch_shadow_of[14] = -1;
    ext_count_branch_shadow_of[15] = -1;
    ext_count_branch_shadow_of[16] = -1;
    ext_count_branch_shadow_of[17] = -1;
    ext_count_branch_shadow_of[18] = -1;
    ext_count_branch_shadow_of[19] = -1;
    ext_count_branch_shadow_of[20] = -1;
    ext_count_branch_shadow_of[21] = -1;
    ext_count_branch_shadow_of[22] = -1;
    ext_count_branch_shadow_of[23] = -1;
    ext_count_branch_shadow_of[24] = -1;
    ext_count_branch_shadow_of[25] = -1;
    ext_count_branch_shadow_of[26] = -1;
    ext_count_branch_shadow_of[27] = -1;
    ext_count_branch_shadow_of[28] = -1;
    ext_count_branch_shadow_of[29] = -1;
    ext_count_branch_shadow_of[30] = -1;
    ext_count_branch_shadow_of[31] = -1;
    ext_count_branch_shadow_of[32] = -1;
    ext_count_branch_shadow_of[33] = -1;
    ext_count_branch_shadow_of[34] = -1;
    ext_count_branch_shadow_of[35] = -1;
    ext_count_branch_shadow_of[36] = -1;
    ext_count_branch_shadow_of[37] = -1;
    ext_count_branch_shadow_of[38] = -1;
    ext_count_branch_shadow_of[39] = -1;
    ext_count_branch_shadow_of[40] = -1;
    ext_count_branch_shadow_of[41] = -1;
    ext_count_branch_shadow_of[42] = -1;
    ext_count_branch_shadow_of[43] = -1;
    ext_count_branch_shadow_of[44] = -1;
    ext_count_branch_shadow_of[45] = -1;
    ext_count_branch_shadow_of[46] = -1;
    ext_count_branch_shadow_of[47] = -1;
    ext_count_branch_shadow_of[48] = -1;
end
assign ext_count_branch_bus[0] = (is_movem_idx_full);
assign ext_count_branch_val[0] = (movem_ext_count);
assign ext_count_branch_bus[1] = (is_cmp2chk2_idx_full);
assign ext_count_branch_val[1] = (cmp2chk2_ext_count);
assign ext_count_branch_bus[2] = (is_move_mm_absw_idxdst_full || is_move_mm_pcrel_idxdst_full);
assign ext_count_branch_val[2] = (move_mm_idxdst_ext_count);
assign ext_count_branch_bus[3] = (is_move_mm_immw_idxdst_full);
assign ext_count_branch_val[3] = (move_mm_immw_idxdst_ext_count);
assign ext_count_branch_bus[4] = (is_move_mm_imml_idxdst_full);
assign ext_count_branch_val[4] = (move_mm_imml_idxdst_ext_count);
assign ext_count_branch_bus[5] = (is_move_mm_absl_idxdst_full);
assign ext_count_branch_val[5] = (move_mm_absl_idxdst_ext_count);
assign ext_count_branch_bus[6] = (is_move_mm_plainsrc_idxdst_full);
assign ext_count_branch_val[6] = (move_mm_plainsrc_idxdst_ext_count);
assign ext_count_branch_bus[7] = (is_move_mm_d16src_idxdst_full);
assign ext_count_branch_val[7] = (move_mm_d16src_idxdst_ext_count);
assign ext_count_branch_bus[8] = (is_move_idx_src_memdst_full);
assign ext_count_branch_val[8] = (move_idx_src_memdst_ext_count);
assign ext_count_branch_bus[9] = (is_memind_full);
assign ext_count_branch_val[9] = (memind_ext_count);
assign ext_count_branch_bus[10] = (is_imm_g0);
assign ext_count_branch_val[10] = (((f_dn != 3'b100) && (f_ss == 2'b10)) ? 3'd2 : 3'd1);
assign ext_count_branch_bus[11] = (is_imm_g0_absl);
assign ext_count_branch_val[11] = ((f_ss == 2'b10) ? 3'd4 : 3'd3);
assign ext_count_branch_bus[12] = (is_imm_g0_d16_or_absw);
assign ext_count_branch_val[12] = ((f_ss == 2'b10) ? 3'd3 : 3'd2);
assign ext_count_branch_bus[13] = (is_imm_g0_mem);
assign ext_count_branch_val[13] = ((f_ss == 2'b10) ? 3'd2 : 3'd1);
assign ext_count_branch_bus[14] = (is_move_mm && move_mm_total_ext_w >= 3'd4);
assign ext_count_branch_val[14] = (3'd4);
assign ext_count_branch_bus[15] = (is_move_mm && move_mm_total_ext_w == 3'd3);
assign ext_count_branch_val[15] = (3'd3);
assign ext_count_branch_bus[16] = (is_move_mm && move_mm_total_ext_w == 3'd2);
assign ext_count_branch_val[16] = (3'd2);
assign ext_count_branch_bus[17] = (is_move_mm && move_mm_total_ext_w == 3'd1);
assign ext_count_branch_val[17] = (3'd1);
assign ext_count_branch_bus[18] = ((f_group == 4'h5) && (f_ss == 2'b11) && (f_mode == 3'b111) && (f_reg == 3'b000));
assign ext_count_branch_val[18] = (3'd1);
assign ext_count_branch_bus[19] = ((f_group == 4'h0) && !f_dir && (f_ss == 2'b11) && (f_dn == 3'b110 || f_dn == 3'b111) && (f_mode == 3'b111) && (f_reg == 3'b100));
assign ext_count_branch_val[19] = (3'd2);
assign ext_count_branch_bus[20] = ((f_group == 4'h1 || f_group == 4'h2 || f_group == 4'h3) && (f_mode == 3'b111) && (f_reg == 3'b100) && (f_move_dst_mode_s == 3'b000 || f_move_dst_mode_s == 3'b001));
assign ext_count_branch_val[20] = ((f_group == 4'h2) ? 3'd2 : 3'd1);
assign ext_count_branch_bus[21] = (instr_word == 16'h46FC || instr_word == 16'h44FC);
assign ext_count_branch_val[21] = (3'd1);
assign ext_count_branch_bus[22] = ((f_group == 4'h4) && !f_dir && (f_ss == 2'b11) && (f_dn == 3'b000 || f_dn == 3'b011 || f_dn == 3'b010) && (f_mode == 3'b111) && (f_reg == 3'b001));
assign ext_count_branch_val[22] = (3'd2);
assign ext_count_branch_bus[23] = ((f_group == 4'h4) && !f_dir && (f_ss == 2'b11) && (f_dn == 3'b000 || f_dn == 3'b011 || f_dn == 3'b010) && (f_mode == 3'b101 || f_mode == 3'b110 || (f_mode == 3'b111 && (f_reg == 3'b000 || f_reg == 3'b010 || f_reg == 3'b011))));
assign ext_count_branch_val[23] = (3'd1);
assign ext_count_branch_bus[24] = ((f_group == 4'h1 || f_group == 4'h2 || f_group == 4'h3) && (f_move_dst_mode_s == 3'b110) && (f_mode == 3'b111) && (f_reg == 3'b100));
assign ext_count_branch_val[24] = ((f_group == 4'h2) ? 3'd3 : 3'd2);
assign ext_count_branch_bus[25] = ((f_group == 4'h1 || f_group == 4'h2 || f_group == 4'h3) && (f_move_dst_mode_s == 3'b110) && (f_mode == 3'b000 || f_mode == 3'b001));
assign ext_count_branch_val[25] = (3'd1);
assign ext_count_branch_bus[26] = ((f_group == 4'h0) && !f_dir && (f_dn == 3'b100) && (f_mode == 3'b111 && f_reg == 3'b001));
assign ext_count_branch_val[26] = (3'd3);
assign ext_count_branch_bus[27] = ((f_group == 4'h0) && !f_dir && (f_dn == 3'b100) && (f_mode == 3'b101 || f_mode == 3'b110 || (f_mode == 3'b111 && (f_reg == 3'b000 || f_reg == 3'b010 || f_reg == 3'b011))));
assign ext_count_branch_val[27] = (3'd2);
assign ext_count_branch_bus[28] = ((f_group == 4'h0) && f_dir && (f_mode == 3'b111 && f_reg == 3'b001));
assign ext_count_branch_val[28] = (3'd2);
assign ext_count_branch_bus[29] = ((f_group == 4'h0) && f_dir && (f_mode == 3'b101 || f_mode == 3'b110 || (f_mode == 3'b111 && (f_reg == 3'b000 || f_reg == 3'b010 || f_reg == 3'b011 || f_reg == 3'b100))));
assign ext_count_branch_val[29] = (3'd1);
assign ext_count_branch_bus[30] = ((f_group == 4'h5) && (f_ss == 2'b11) && (f_mode == 3'b111) && (f_reg == 3'b001 || f_reg == 3'b011));
assign ext_count_branch_val[30] = (3'd2);
assign ext_count_branch_bus[31] = ((f_group == 4'h5) && (f_ss == 2'b11) && (f_mode == 3'b101 || f_mode == 3'b110));
assign ext_count_branch_val[31] = (3'd1);
assign ext_count_branch_bus[32] = ((f_group == 4'h4) && !f_dir && (f_dn == 3'b100) && (f_ss == 2'b00) && (f_mode == 3'b111 && f_reg == 3'b001));
assign ext_count_branch_val[32] = (3'd2);
assign ext_count_branch_bus[33] = ((f_group == 4'h4) && !f_dir && (f_dn == 3'b100) && (f_ss == 2'b00) && (f_mode == 3'b101 || f_mode == 3'b110 || (f_mode == 3'b111 && f_reg == 3'b000)));
assign ext_count_branch_val[33] = (3'd1);
assign ext_count_branch_bus[34] = ((f_group == 4'h4) && !f_dir && (f_dn == 3'b101) && (f_ss == 2'b11) && (f_mode == 3'b101 || f_mode == 3'b110 || (f_mode == 3'b111 && f_reg == 3'b000)));
assign ext_count_branch_val[34] = (3'd1);
assign ext_count_branch_bus[35] = ((f_group == 4'h4) && !f_dir && (f_dn == 3'b101) && (f_ss == 2'b11) && (f_mode == 3'b111 && f_reg == 3'b001));
assign ext_count_branch_val[35] = (3'd2);
assign ext_count_branch_bus[36] = ((f_group == 4'h4) && !f_dir && (f_ss != 2'b11) && (f_dn == 3'b000 || f_dn == 3'b001 || f_dn == 3'b010 || f_dn == 3'b011 || f_dn == 3'b101) && (f_mode == 3'b101 || f_mode == 3'b110 || (f_mode == 3'b111 && (f_reg == 3'b000 || (f_dn == 3'b101 && f_reg == 3'b010)))));
assign ext_count_branch_val[36] = (3'd1);
assign ext_count_branch_bus[37] = ((f_group == 4'h4) && !f_dir && (f_ss != 2'b11) && (f_dn == 3'b000 || f_dn == 3'b001 || f_dn == 3'b010 || f_dn == 3'b011 || f_dn == 3'b101) && (f_mode == 3'b111 && f_reg == 3'b001));
assign ext_count_branch_val[37] = (3'd2);
assign ext_count_branch_bus[38] = ((f_group == 4'he) && (f_ss == 2'b11) && !f_dn[2] && (f_mode == 3'b101 || f_mode == 3'b110 || (f_mode == 3'b111 && f_reg == 3'b000)));
assign ext_count_branch_val[38] = (3'd1);
assign ext_count_branch_bus[39] = ((f_group == 4'he) && (f_ss == 2'b11) && !f_dn[2] && (f_mode == 3'b111 && f_reg == 3'b001));
assign ext_count_branch_val[39] = (3'd2);
assign ext_count_branch_bus[40] = ((f_group == 4'h0) && !f_dir && (f_ss == 2'b11) && !f_dn[2] && (f_dn != 3'b011) && (f_mode == 3'b101 || f_mode == 3'b110 || (f_mode == 3'b111 && (f_reg == 3'b000 || f_reg == 3'b010))));
assign ext_count_branch_val[40] = (3'd2);
assign ext_count_branch_bus[41] = ((f_group == 4'h0) && !f_dir && (f_ss == 2'b11) && !f_dn[2] && (f_dn != 3'b011) && (f_mode == 3'b010));
assign ext_count_branch_val[41] = (3'd1);
assign ext_count_branch_bus[42] = ((f_group == 4'h4) && f_dir && (f_ss == 2'b10 || f_ss == 2'b00) && (f_mode == 3'b111) && (f_reg == 3'b100));
assign ext_count_branch_val[42] = ((f_ss == 2'b10) ? 3'd1 : 3'd2);
assign ext_count_branch_bus[43] = ((f_group == 4'h4) && f_dir && (f_ss == 2'b10 || f_ss == 2'b00) && (f_mode == 3'b111) && (f_reg == 3'b001));
assign ext_count_branch_val[43] = (3'd2);
assign ext_count_branch_bus[44] = ((f_group == 4'h4) && f_dir && (f_ss == 2'b10 || f_ss == 2'b00) && (f_mode == 3'b101 || f_mode == 3'b110 || (f_mode == 3'b111 && (f_reg == 3'b000 || f_reg == 3'b010 || f_reg == 3'b011))));
assign ext_count_branch_val[44] = (3'd1);
assign ext_count_branch_bus[45] = (is_movem_3ext || is_muldivl_3ext);
assign ext_count_branch_val[45] = (3'd3);
assign ext_count_branch_bus[46] = (is_branch_l || is_abs_long || (is_adda_suba_cmpa_imm && f_dir) || is_pea_abs_long || is_link_l || is_moves_long_ea || is_alu_mem_src_long || is_addq_subq_ext_long || is_movem_2ext || (is_alu_imm_dn && f_ss == 2'b10) || is_muldivl_2ext || ((is_cpsave || is_cprestore) && (f_mode == 3'b111) && (f_reg == 3'b001)));
assign ext_count_branch_val[46] = (3'd2);
assign ext_count_branch_bus[47] = (is_branch_w || is_dbcc || is_move_d16 || is_lea_d16 || is_jsr_jmp_d16 || is_link || is_abs_short || is_pc_rel || is_move_idx_src || is_lea_idx || is_jmp_idx || is_jsr_idx || is_movem || is_movep || is_adda_suba_cmpa_imm || is_ori_andi_eori_sr || is_muldivl || is_muldivl_mem || is_rtd || is_stop_opcode || is_bf || is_pack_unpk || is_moves || (is_alu_mem_src && !is_alu_mem_src_long) || (is_addq_subq_ext && !is_addq_subq_ext_long) || (is_alu_imm_dn && f_ss != 2'b10) || is_muldiv_imm || (is_pea && (f_mode == 3'b101)) || (is_pea && (f_mode == 3'b110)) || (is_pea && (f_mode == 3'b111) && (instr_word[2:0] == 3'b000)) || (is_pea && (f_mode == 3'b111) && (instr_word[2:0] == 3'b010)) || (is_pea && (f_mode == 3'b111) && (instr_word[2:0] == 3'b011)) || ((is_cpsave || is_cprestore) && (f_mode == 3'b101)) || ((is_cpsave || is_cprestore) && (f_mode == 3'b110)) || ((is_cpsave || is_cprestore) && (f_mode == 3'b111) && (f_reg == 3'b000)) || ((is_cpsave || is_cprestore) && (f_mode == 3'b111) && (f_reg == 3'b010)) || ((is_cpsave || is_cprestore) && (f_mode == 3'b111) && (f_reg == 3'b011)) || ((f_group == 4'h5) && (f_ss == 2'b11) && (f_mode == 3'b111) && (f_reg == 3'b010)) || ((f_group == 4'h0) && !f_dir && (f_ss == 2'b11) && (f_dn == 3'b101 || f_dn == 3'b011 || f_dn == 3'b111) && (f_mode == 3'b010)) || ((f_group == 4'h0) && !f_dir && (f_dn == 3'b100) && (f_mode == 3'b010 || f_mode == 3'b011 || f_mode == 3'b100)) || (instr_word == 16'h4E7A || instr_word == 16'h4E7B));
assign ext_count_branch_val[47] = (3'd1);
assign ext_count_branch_bus[48] = ((f_group == 4'hf) && (f_dn == 3'b000));
assign ext_count_branch_val[48] = (3'd1);

// For failure-message readability only.
function automatic string ext_count_branch_desc(input int idx);
    case (idx)
        0: ext_count_branch_desc = "is_movem_idx_full";
        1: ext_count_branch_desc = "is_cmp2chk2_idx_full";
        2: ext_count_branch_desc = "is_move_mm_absw_idxdst_full || is_move_mm_pcrel_idxdst_full";
        3: ext_count_branch_desc = "is_move_mm_immw_idxdst_full";
        4: ext_count_branch_desc = "is_move_mm_imml_idxdst_full";
        5: ext_count_branch_desc = "is_move_mm_absl_idxdst_full";
        6: ext_count_branch_desc = "is_move_mm_plainsrc_idxdst_full";
        7: ext_count_branch_desc = "is_move_mm_d16src_idxdst_full";
        8: ext_count_branch_desc = "is_move_idx_src_memdst_full";
        9: ext_count_branch_desc = "is_memind_full";
        10: ext_count_branch_desc = "is_imm_g0";
        11: ext_count_branch_desc = "is_imm_g0_absl";
        12: ext_count_branch_desc = "is_imm_g0_d16_or_absw";
        13: ext_count_branch_desc = "is_imm_g0_mem";
        14: ext_count_branch_desc = "is_move_mm && move_mm_total_ext_w >= 3'd4";
        15: ext_count_branch_desc = "is_move_mm && move_mm_total_ext_w == 3'd3";
        16: ext_count_branch_desc = "is_move_mm && move_mm_total_ext_w == 3'd2";
        17: ext_count_branch_desc = "is_move_mm && move_mm_total_ext_w == 3'd1";
        18: ext_count_branch_desc = "(f_group == 4'h5) && (f_ss == 2'b11) && (f_mode == 3'b111) && (f_reg == 3'b000)";
        19: ext_count_branch_desc = "(f_group == 4'h0) && !f_dir && (f_ss == 2'b11) && (f_dn == 3'b110 || f_dn == 3'b111) && (f_mode == 3'b111) && (f_reg == 3'b100)";
        20: ext_count_branch_desc = "(f_group == 4'h1 || f_group == 4'h2 || f_group == 4'h3) && (f_mode == 3'b111) && (f_reg == 3'b100) && (f_move_dst_mode_s == 3'b000 || f_move_dst_mode_s == 3'b001)";
        21: ext_count_branch_desc = "instr_word == 16'h46FC || instr_word == 16'h44FC";
        22: ext_count_branch_desc = "(f_group == 4'h4) && !f_dir && (f_ss == 2'b11) && (f_dn == 3'b000 || f_dn == 3'b011 || f_dn == 3'b010) && (f_mode == 3'b111) && (f_reg == 3'b001)";
        23: ext_count_branch_desc = "(f_group == 4'h4) && !f_dir && (f_ss == 2'b11) && (f_dn == 3'b000 || f_dn == 3'b011 || f_dn == 3'b010) && (f_mode == 3'b101 || f_mode == 3'b110 || (f_mode == 3'b111 && (f_reg == 3'b000 || f_reg == 3'b010 || f_reg == 3'b011)))";
        24: ext_count_branch_desc = "(f_group == 4'h1 || f_group == 4'h2 || f_group == 4'h3) && (f_move_dst_mode_s == 3'b110) && (f_mode == 3'b111) && (f_reg == 3'b100)";
        25: ext_count_branch_desc = "(f_group == 4'h1 || f_group == 4'h2 || f_group == 4'h3) && (f_move_dst_mode_s == 3'b110) && (f_mode == 3'b000 || f_mode == 3'b001)";
        26: ext_count_branch_desc = "(f_group == 4'h0) && !f_dir && (f_dn == 3'b100) && (f_mode == 3'b111 && f_reg == 3'b001)";
        27: ext_count_branch_desc = "(f_group == 4'h0) && !f_dir && (f_dn == 3'b100) && (f_mode == 3'b101 || f_mode == 3'b110 || (f_mode == 3'b111 && (f_reg == 3'b000 || f_reg == 3'b010 || f_reg == 3'b011)))";
        28: ext_count_branch_desc = "(f_group == 4'h0) && f_dir && (f_mode == 3'b111 && f_reg == 3'b001)";
        29: ext_count_branch_desc = "(f_group == 4'h0) && f_dir && (f_mode == 3'b101 || f_mode == 3'b110 || (f_mode == 3'b111 && (f_reg == 3'b000 || f_reg == 3'b010 || f_reg == 3'b011 || f_reg == 3'b100)))";
        30: ext_count_branch_desc = "(f_group == 4'h5) && (f_ss == 2'b11) && (f_mode == 3'b111) && (f_reg == 3'b001 || f_reg == 3'b011)";
        31: ext_count_branch_desc = "(f_group == 4'h5) && (f_ss == 2'b11) && (f_mode == 3'b101 || f_mode == 3'b110)";
        32: ext_count_branch_desc = "(f_group == 4'h4) && !f_dir && (f_dn == 3'b100) && (f_ss == 2'b00) && (f_mode == 3'b111 && f_reg == 3'b001)";
        33: ext_count_branch_desc = "(f_group == 4'h4) && !f_dir && (f_dn == 3'b100) && (f_ss == 2'b00) && (f_mode == 3'b101 || f_mode == 3'b110 || (f_mode == 3'b111 && f_reg == 3'b000))";
        34: ext_count_branch_desc = "(f_group == 4'h4) && !f_dir && (f_dn == 3'b101) && (f_ss == 2'b11) && (f_mode == 3'b101 || f_mode == 3'b110 || (f_mode == 3'b111 && f_reg == 3'b000))";
        35: ext_count_branch_desc = "(f_group == 4'h4) && !f_dir && (f_dn == 3'b101) && (f_ss == 2'b11) && (f_mode == 3'b111 && f_reg == 3'b001)";
        36: ext_count_branch_desc = "(f_group == 4'h4) && !f_dir && (f_ss != 2'b11) && (f_dn == 3'b000 || f_dn == 3'b001 || f_dn == 3'b010 || f_dn == 3'b011 || f_dn == 3'b101) && (f_mode == 3'b101 || f_mode == 3'b110 || (f_mode == 3'b111 && (f_reg == 3'b000 || (f_dn == 3'b101 && f_reg == 3'b010))))";
        37: ext_count_branch_desc = "(f_group == 4'h4) && !f_dir && (f_ss != 2'b11) && (f_dn == 3'b000 || f_dn == 3'b001 || f_dn == 3'b010 || f_dn == 3'b011 || f_dn == 3'b101) && (f_mode == 3'b111 && f_reg == 3'b001)";
        38: ext_count_branch_desc = "(f_group == 4'he) && (f_ss == 2'b11) && !f_dn[2] && (f_mode == 3'b101 || f_mode == 3'b110 || (f_mode == 3'b111 && f_reg == 3'b000))";
        39: ext_count_branch_desc = "(f_group == 4'he) && (f_ss == 2'b11) && !f_dn[2] && (f_mode == 3'b111 && f_reg == 3'b001)";
        40: ext_count_branch_desc = "(f_group == 4'h0) && !f_dir && (f_ss == 2'b11) && !f_dn[2] && (f_dn != 3'b011) && (f_mode == 3'b101 || f_mode == 3'b110 || (f_mode == 3'b111 && (f_reg == 3'b000 || f_reg == 3'b010)))";
        41: ext_count_branch_desc = "(f_group == 4'h0) && !f_dir && (f_ss == 2'b11) && !f_dn[2] && (f_dn != 3'b011) && (f_mode == 3'b010)";
        42: ext_count_branch_desc = "(f_group == 4'h4) && f_dir && (f_ss == 2'b10 || f_ss == 2'b00) && (f_mode == 3'b111) && (f_reg == 3'b100)";
        43: ext_count_branch_desc = "(f_group == 4'h4) && f_dir && (f_ss == 2'b10 || f_ss == 2'b00) && (f_mode == 3'b111) && (f_reg == 3'b001)";
        44: ext_count_branch_desc = "(f_group == 4'h4) && f_dir && (f_ss == 2'b10 || f_ss == 2'b00) && (f_mode == 3'b101 || f_mode == 3'b110 || (f_mode == 3'b111 && (f_reg == 3'b000 || f_reg == 3'b010 || f_reg == 3'b011)))";
        45: ext_count_branch_desc = "is_movem_3ext || is_muldivl_3ext";
        46: ext_count_branch_desc = "is_branch_l || is_abs_long || (is_adda_suba_cmpa_imm && f_dir) || is_pea_abs_long || is_link_l || is_moves_long_ea || is_alu_mem_src_long || is_addq_subq_ext_long || is_movem_2ext || (is_alu_imm_dn && f_ss == 2'b10) || is_muldivl_2ext || ((is_cpsave || is_cprestore) && (f_mode == 3'b111) && (f_reg == 3'b001))";
        47: ext_count_branch_desc = "is_branch_w || is_dbcc || is_move_d16 || is_lea_d16 || is_jsr_jmp_d16 || is_link || is_abs_short || is_pc_rel || is_move_idx_src || is_lea_idx || is_jmp_idx || is_jsr_idx || is_movem || is_movep || is_adda_suba_cmpa_imm || is_ori_andi_eori_sr || is_muldivl || is_muldivl_mem || is_rtd || is_stop_opcode || is_bf || is_pack_unpk || is_moves || (is_alu_mem_src && !is_alu_mem_src_long) || (is_addq_subq_ext && !is_addq_subq_ext_long) || (is_alu_imm_dn && f_ss != 2'b10) || is_muldiv_imm || (is_pea && (f_mode == 3'b101)) || (is_pea && (f_mode == 3'b110)) || (is_pea && (f_mode == 3'b111) && (instr_word[2:0] == 3'b000)) || (is_pea && (f_mode == 3'b111) && (instr_word[2:0] == 3'b010)) || (is_pea && (f_mode == 3'b111) && (instr_word[2:0] == 3'b011)) || ((is_cpsave || is_cprestore) && (f_mode == 3'b101)) || ((is_cpsave || is_cprestore) && (f_mode == 3'b110)) || ((is_cpsave || is_cprestore) && (f_mode == 3'b111) && (f_reg == 3'b000)) || ((is_cpsave || is_cprestore) && (f_mode == 3'b111) && (f_reg == 3'b010)) || ((is_cpsave || is_cprestore) && (f_mode == 3'b111) && (f_reg == 3'b011)) || ((f_group == 4'h5) && (f_ss == 2'b11) && (f_mode == 3'b111) && (f_reg == 3'b010)) || ((f_group == 4'h0) && !f_dir && (f_ss == 2'b11) && (f_dn == 3'b101 || f_dn == 3'b011 || f_dn == 3'b111) && (f_mode == 3'b010)) || ((f_group == 4'h0) && !f_dir && (f_dn == 3'b100) && (f_mode == 3'b010 || f_mode == 3'b011 || f_mode == 3'b100)) || (instr_word == 16'h4E7A || instr_word == 16'h4E7B)";
        48: ext_count_branch_desc = "(f_group == 4'hf) && (f_dn == 3'b000)";
        default: ext_count_branch_desc = "?";
    endcase
endfunction
