`default_nettype none
`timescale 1ps/1ps

// Tom Harte SingleStepTests m68000 one-instruction testbench
//
// Usage: vvp sim/harte_dat +hexfile=<path> [+cycles=<N>]
//
// Loads a sparse hex file (generated by scripts/gen_harte_hex.py), runs until
// STOP, then prints:
//   REGSTATE D0=.. .. A7=.. SR=.. PC=..
//   MEMWRITE <24-bit-addr> <byte-val>    (one line per byte written)
//
// Memory is addressed as ext_a[23:2] — the 68030 drives full 32-bit addresses
// but test data is within the 24-bit 68000 address space, so we naturally
// shadow the upper byte.

module harte_tb;

    logic clk_4x = 0;
    always #5 clk_4x = ~clk_4x;

    logic rst_n = 0;

    // ── External pin buses ────────────────────────────────────────────────────
    logic [31:0] ext_a;
    logic [31:0] ext_d_out;
    logic        ext_d_oe;
    logic        ext_as_n, ext_ds_n, ext_rw;
    logic [2:0]  ext_fc;
    logic [1:0]  ext_siz;
    logic        ext_ecs_n, ext_ocs_n, ext_rstout_n, ext_cbreq_n;
    logic        ext_e, ext_bg_n;
    logic        bus_halted, eu_addr_err, ifu_addr_err;
    logic        eu_stop_out;

    logic        sterm_n = 1'b1;
    logic        berr_n  = 1'b1;
    logic        halt_n  = 1'b1;
    logic        avec_n  = 1'b1;
    logic        vpa_n   = 1'b1;
    logic [2:0]  ipl_n   = 3'b111;
    logic        br_n    = 1'b1;
    logic        bgack_n = 1'b1;
    logic        cback_n = 1'b0;

    // ── Memory model ──────────────────────────────────────────────────────────
    // 4M × 32-bit words (16 MB) — full 24-bit address space, no folding.
    // ext_a[23:2] gives a unique 22-bit word index for every aligned 32-bit
    // word in the 68000/030 24-bit address space, eliminating all aliasing.
    localparam int MEM_WORDS = 1 << 22;   // 4M words = 16 MB
    logic [31:0] mem [0:MEM_WORDS-1];

    string hexfile;
    initial begin
        if (!$value$plusargs("hexfile=%s", hexfile))
            hexfile = "tests/harte/test.hex";
        $readmemh(hexfile, mem);
    end

    wire [21:0] mem_idx = ext_a[23:2];   // 22-bit word index, full 24-bit space

    // Register the read one cycle after DS+AS assert, avoiding a continuous
    // assignment that Icarus re-evaluates on every write to the array.
    // For a misaligned longword (siz=00, A[1:0]=10) the 4 bytes span two
    // aligned 32-bit words; combine them so the DUT receives the right data.
    logic [31:0] rd_word_r;
    always_ff @(posedge clk_4x) begin
        if (!ext_ds_n && !ext_as_n && ext_rw) begin
            if (ext_siz == 2'b00 && ext_a[1:0] == 2'b10)
                rd_word_r <= {mem[mem_idx][15:0], mem[mem_idx+1][31:16]};
            else
                rd_word_r <= mem[mem_idx];
        end
    end

    // DSACK: one-cycle latency (respond cycle after DS asserts)
    logic ds_active_r;
    always_ff @(posedge clk_4x or negedge rst_n) begin
        if (!rst_n) ds_active_r <= 1'b0;
        else        ds_active_r <= !ext_ds_n & !ext_as_n;
    end
    wire dsack0_n = ~ds_active_r;
    wire dsack1_n = ~ds_active_r;

    wire [31:0] ext_d_in = ds_active_r ? rd_word_r : '0;

    // ── Write capture ─────────────────────────────────────────────────────────
    // One cycle after DS goes active on a write, latch data into memory.
    // Log the real 24-bit address (not the folded 16-bit index) for comparison.
    always_ff @(posedge clk_4x) begin
        if (ds_active_r && !ext_ds_n && !ext_as_n && !ext_rw && ext_d_oe) begin
            case ({ext_siz, ext_a[1:0]})
                4'b00_00: begin
                    mem[mem_idx]        <= ext_d_out;
                    $display("MEMWRITE %06x %02x", {ext_a[23:2],2'b00}, ext_d_out[31:24]);
                    $display("MEMWRITE %06x %02x", {ext_a[23:2],2'b01}, ext_d_out[23:16]);
                    $display("MEMWRITE %06x %02x", {ext_a[23:2],2'b10}, ext_d_out[15:8]);
                    $display("MEMWRITE %06x %02x", {ext_a[23:2],2'b11}, ext_d_out[7:0]);
                end
                4'b00_10: begin  // Misaligned longword: spans two aligned 32-bit words
                    mem[mem_idx][15:0]    <= ext_d_out[31:16];
                    mem[mem_idx+1][31:16] <= ext_d_out[15:0];
                    $display("MEMWRITE %06x %02x", {ext_a[23:2],2'b10},   ext_d_out[31:24]);
                    $display("MEMWRITE %06x %02x", {ext_a[23:2],2'b11},   ext_d_out[23:16]);
                    $display("MEMWRITE %06x %02x", {ext_a[23:2]+22'd1,2'b00}, ext_d_out[15:8]);
                    $display("MEMWRITE %06x %02x", {ext_a[23:2]+22'd1,2'b01}, ext_d_out[7:0]);
                end
                4'b10_00: begin
                    mem[mem_idx][31:16] <= ext_d_out[31:16];
                    $display("MEMWRITE %06x %02x", {ext_a[23:2],2'b00}, ext_d_out[31:24]);
                    $display("MEMWRITE %06x %02x", {ext_a[23:2],2'b01}, ext_d_out[23:16]);
                end
                4'b10_10: begin
                    mem[mem_idx][15:0]  <= ext_d_out[15:0];
                    $display("MEMWRITE %06x %02x", {ext_a[23:2],2'b10}, ext_d_out[15:8]);
                    $display("MEMWRITE %06x %02x", {ext_a[23:2],2'b11}, ext_d_out[7:0]);
                end
                4'b01_00: begin
                    mem[mem_idx][31:24] <= ext_d_out[31:24];
                    $display("MEMWRITE %06x %02x", {ext_a[23:2],2'b00}, ext_d_out[31:24]);
                end
                4'b01_01: begin
                    mem[mem_idx][23:16] <= ext_d_out[23:16];
                    $display("MEMWRITE %06x %02x", {ext_a[23:2],2'b01}, ext_d_out[23:16]);
                end
                4'b01_10: begin
                    mem[mem_idx][15:8]  <= ext_d_out[15:8];
                    $display("MEMWRITE %06x %02x", {ext_a[23:2],2'b10}, ext_d_out[15:8]);
                end
                4'b01_11: begin
                    mem[mem_idx][7:0]   <= ext_d_out[7:0];
                    $display("MEMWRITE %06x %02x", {ext_a[23:2],2'b11}, ext_d_out[7:0]);
                end
                default: begin
                    mem[mem_idx]        <= ext_d_out;
                    $display("MEMWRITE %06x %02x", {ext_a[23:2],2'b00}, ext_d_out[31:24]);
                end
            endcase
        end
    end

    // ── DUT ──────────────────────────────────────────────────────────────────
    m68030_top #(.POWERON_RSTO_CLKS(40)) u_top (
        .clk_4x       (clk_4x),
        .rst_n        (rst_n),
        .ext_a        (ext_a),
        .ext_d_out    (ext_d_out),
        .ext_d_oe     (ext_d_oe),
        .ext_d_in     (ext_d_in),
        .ext_as_n     (ext_as_n),
        .ext_ds_n     (ext_ds_n),
        .ext_rw       (ext_rw),
        .ext_fc       (ext_fc),
        .ext_siz      (ext_siz),
        .ext_ecs_n    (ext_ecs_n),
        .ext_ocs_n    (ext_ocs_n),
        .ext_rstout_n (ext_rstout_n),
        .ext_cbreq_n  (ext_cbreq_n),
        .ext_e        (ext_e),
        .ext_bg_n     (ext_bg_n),
        .bus_halted   (bus_halted),
        .eu_addr_err  (eu_addr_err),
        .ifu_addr_err (ifu_addr_err),
        .eu_stop      (eu_stop_out),
        .dsack0_n     (dsack0_n),
        .dsack1_n     (dsack1_n),
        .sterm_n      (sterm_n),
        .berr_n       (berr_n),
        .halt_n       (halt_n),
        .avec_n       (avec_n),
        .vpa_n        (vpa_n),
        .ipl_n        (ipl_n),
        .br_n         (br_n),
        .bgack_n      (bgack_n),
        .cback_n      (cback_n)
    );

    // ── STOP detection ───────────────────────────────────────────────────────
    logic stop_seen = 1'b0;
    always_ff @(posedge clk_4x) begin
        if (eu_stop_out) stop_seen <= 1'b1;
    end

    // Capture SR just before STOP executes (STOP #$2700 overwrites CCR bits).
    // Originally gated on !eu_stop_out, on the (false) assumption that
    // eu_stop_out always goes high exactly one cycle after the last real
    // instruction's own sr_r commit -- true under every fetch-timing
    // profile this project exercised before the I-cache existed (always a
    // real bus cycle, never a same-cycle hit), but NOT a real invariant:
    // an I-cache hit on STOP's own opcode fetch can let it reach EX fast
    // enough to land eu_stop_out on the *exact same cycle* as the
    // preceding instruction's own CCR commit, and gating on !eu_stop_out
    // silently drops that cycle's update, capturing the *stale*,
    // second-to-last value instead (found via Phase 127's own cache
    // plan Step 6 -- confirmed via direct sr_r tracing, not guessed at).
    // A second attempt gated on !stop_seen instead (the one-cycle-later
    // registered version of eu_stop_out), reasoning "capture one more
    // cycle" -- wrong in the *other* direction for RMW-style
    // memory-dest instructions, where multiple cycles separate the real
    // commit from eu_stop_out, and the extra cycle captured STOP's own
    // "#$2700" operand landing in sr_r instead of the tested instruction's
    // own result (also confirmed via direct tracing). A third attempt
    // gated on !stop_sr_wr_en (eu_seq.sv's own combinational
    // ex_valid && ex_is_stop && !stop_r, exactly the cycle STOP's own SR
    // write is about to land) looked right but stop_sr_wr_en is a
    // ONE-CYCLE PULSE, not a level: it drops back to 0 the very next
    // cycle (once stop_r itself becomes 1), which re-opens the capture
    // gate and immediately picks up STOP's now-already-landed "#$2700"
    // value anyway. stop_r itself is the level that actually matters: it
    // goes 1 on the same edge stop_sr_wr_en fires and *stays* 1
    // thereafter, so gating on !stop_r permanently freezes capture from
    // that edge on, correctly keeping whatever sr_r held the cycle before.
    logic [15:0] sr_before_stop;
    always_ff @(posedge clk_4x) begin
        if (!u_top.u_eu.u_seq.stop_r)
            sr_before_stop <= u_top.u_eu.u_rf.sr_r;
    end

    logic any_addr_err = 1'b0;
    always_ff @(posedge clk_4x) begin
        if (eu_addr_err || ifu_addr_err) any_addr_err <= 1'b1;
    end

    // ── Main ─────────────────────────────────────────────────────────────────
    initial begin
        integer cycles;
        rst_n = 0;
        repeat(20) @(posedge clk_4x);
        #1; rst_n = 1;

        if (!$value$plusargs("cycles=%d", cycles)) cycles = 8000;

        fork
            begin : blk_timeout
                repeat(cycles) @(posedge clk_4x);
                disable blk_stop;
            end
            begin : blk_stop
                wait(stop_seen == 1'b1);
                repeat(4) @(posedge clk_4x);
                disable blk_timeout;
            end
        join

        $display("REGSTATE D0=%h D1=%h D2=%h D3=%h D4=%h D5=%h D6=%h D7=%h A0=%h A1=%h A2=%h A3=%h A4=%h A5=%h A6=%h A7=%h SR=%h PC=%h",
            u_top.u_eu.u_rf.d_reg[0], u_top.u_eu.u_rf.d_reg[1],
            u_top.u_eu.u_rf.d_reg[2], u_top.u_eu.u_rf.d_reg[3],
            u_top.u_eu.u_rf.d_reg[4], u_top.u_eu.u_rf.d_reg[5],
            u_top.u_eu.u_rf.d_reg[6], u_top.u_eu.u_rf.d_reg[7],
            u_top.u_eu.u_rf.a_reg[0], u_top.u_eu.u_rf.a_reg[1],
            u_top.u_eu.u_rf.a_reg[2], u_top.u_eu.u_rf.a_reg[3],
            u_top.u_eu.u_rf.a_reg[4], u_top.u_eu.u_rf.a_reg[5],
            u_top.u_eu.u_rf.a_reg[6], u_top.u_eu.u_rf.a7_current,
            sr_before_stop,            u_top.u_eu.u_rf.pc_r);

        if (!stop_seen)
            $display("TIMEOUT");
        else if (any_addr_err)
            $display("ADDRERR");
        else
            $display("OK");

        $finish;
    end

endmodule
